# Generated by Django 3.1.7 on 2021-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='Enthusiastic....', help_text='A short sentence about you as a student', max_length=255),
        ),
    ]
