# Generated by Django 3.1.2 on 2021-04-30 19:58

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, populate_from='title', unique=True)),
                ('industry', models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Automobile', 'Automobile'), ('Banking and Finance', 'Banking And Finance'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Engineering', 'Engineering'), ('Health', 'Health'), ('Information Technology', 'I T'), ('Logistics', 'Logistics'), ('Transportation', 'Transportation')], default='Information Technology', max_length=25)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, default=None)),
                ('short_note', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('industry', models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Automobile', 'Automobile'), ('Banking and Finance', 'Banking And Finance'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Engineering', 'Engineering'), ('Health', 'Health'), ('Information Technology', 'I T'), ('Logistics', 'Logistics'), ('Transportation', 'Transportation')], default='Information Technology', max_length=25)),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique=True)),
                ('location', models.CharField(max_length=150)),
                ('is_full_time', models.BooleanField()),
                ('qualification', models.TextField(blank=True, default=None)),
                ('description', models.TextField(blank=True, default=None)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.category')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.firm')),
            ],
        ),
    ]
