# Generated by Django 3.1.7 on 2021-04-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
    ]
