# Generated by Django 3.1.7 on 2021-04-01 13:39

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_part_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='lesson',
        ),
        migrations.AddField(
            model_name='part',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('material', models.FileField(blank=True, null=True, upload_to='')),
                ('can_preview', models.BooleanField(default=False)),
                ('duration', models.FloatField(validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(30.0)])),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subcategory')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.part')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section')),
            ],
        ),
    ]
