# Generated by Django 3.1.7 on 2021-04-10 12:18

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_featurereview_studentfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='live_class_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator(20), djmoney.models.validators.MaxMoneyValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='our_live_class_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator(40), djmoney.models.validators.MaxMoneyValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='self_paced_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator(5), djmoney.models.validators.MaxMoneyValidator(50)]),
        ),
    ]
