# Generated by Django 3.1.7 on 2021-04-10 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210410_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeatureReview',
            new_name='FeaturedReview',
        ),
        migrations.AddField(
            model_name='studentfeedback',
            name='ratings',
            field=models.FloatField(default=4.5, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
