# Generated by Django 3.1.7 on 2021-04-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210410_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredreview',
            name='short_note',
            field=models.CharField(default='Thanks', max_length=50),
        ),
    ]
