# Generated by Django 3.1.7 on 2021-04-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_featuredreview_short_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(max_length=20, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumb_nail',
            field=models.FileField(help_text='A cover image for your Course', upload_to=''),
        ),
    ]
