# Generated by Django 3.1.7 on 2021-04-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210412_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_content', to='courses.course'),
        ),
    ]
